version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/rohith-intelops/socialmedia"
